[package]
name = "rustybrot-lib"
version = "0.0.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
description = ""
keywords = ["mandelbrot", "buddhabrot"]
license = "MIT/Apache-2.0"

[dependencies]
error-chain = "*"
rand = "*"
num = "*"

